name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go mod tidy
      - name: Build
        run: |
          CGO_ENABLED=0 go build -v .
          pwd

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Hitokoto
          path: /home/runner/work/Hitokoto/Hitokoto

  dockerfile:
    name: Build Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@master
        with:
          name: Hitokoto
          path: /home/runner/work/Hitokoto/Hitokoto

      - id: create_docker_tags
        run: |
          echo "::set-output name=tags::latest,$(git tag -l --sort=-v:refname | head -1 | cut -c 2-)"

      - name: Build & Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          tags: ${{ steps.create_docker_tags.outputs.tags }}

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: Hitokoto

  deploy:
    name: Deploy to Servers
    runs-on: ubuntu-latest
    needs: dockerfile
    steps:
      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
        with:
          host: ${{ secrets.SSH_IP }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          connect_timeout: 10s
          script: |
            docker rm -f Service_Hitokoto || true
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
            docker rmi $DOCKER_NAME || true
            docker pull $DOCKER_NAME
            docker run -dt --name Service_Hitokoto -e TZ=Asia/Shanghai --net "apicon-service" --ip 172.20.0.12 $DOCKER_NAME:latest
